CC=/usr/bin/i586-mingw32msvc-gcc
SOURCES=srcs/main.c srcs/adb.c srcs/misc.c srcs/sensor_listener.c srcs/socket.c

out/AndroVMplayer.exe: ${SOURCES} lib/SDL.dll lib/libOpenglRender.dll
	${CC} -m32 -Iincludes -I../SDL-1.2.15/include/SDL -o out/AndroVMplayer.exe ${SOURCES} lib/SDL.dll lib/libOpenglRender.dll -lmsvcrt -lws2_32
